### PR TITLE
Get correct DV portgroups for the selected resource

### LINKED ISSUE #307: VCH Wizard resource selection
**VIC version:**
VIC 1.3.0

**Deployment details:**
On my vCenter environment, I have 2 clusters, one Management and a Resource one, each cluster has it's own vDS and datastores.
VCH will be provisioned on the Resource cluster only.

**Steps to reproduce:**
When creating the VCH through the Wizard, it just shows the PortGroups from the vDS of the Management Cluster.

compute

networks

captura de tela 2018-01-17 as 13 45 38

**Expected behavior:**
The PortGroups and the Datastores should be the ones available based on the Compute Resource selected on the Compute Capacity section only, everything else, should be filter out.

### PR DESCRIPTION
**Pull request by jooskim**
Fixes #307 

Test steps:
1. Make sure distributed virtual switch named "DSwitch 2" is not in the VC inventory
    1. govc object.destroy '/Datacenter/network/DSwitch 2
2. Create a new distributed virtual switch named "DSwitch 2"
    1. govc dvs.create -dc=Datacenter 'DSwitch 2'
3. Create port groups: net1, net2
    1. govc dvs.portgroup.add -nports 12 -dc=Datacenter -dvs='DSwitch 2' net1
    2. govc dvs.portgroup.add -nports 12 -dc=Datacenter -dvs='DSwitch 2' net2
4. Add an idle standalone host to "DSwitch 2" (make sure to add the host to the VC beforehand!)
    1. govc dvs.add -dvs='DSwitch 2' -pnic=vmnic1 -host.ip=$HOST_IP $HOST_IP
5. Open the VCH Create wizard and select "Cluster" as compute resource
6. Proceed to the "Networks" section, select port groups "bridge" and "network" for the bridge and public networks
7. Navigate backwards to the "Compute Capacity" section and select the standalone host
8. Proceed to the "Capacity section" and select a datastore that has name starting with "datastore1"
9. Proceed to the "Networks" section and select "net1" for bridge and "net2" for public networks
10. Continue through the rest of the steps to finish creating a VCH
11. Check if the VCH is created successfully and delete it once it's created

### CODE REVIEW

**Comment by mdubya66** [comment]
Approved for 1.3.1

**Comment by jooskim** [comment]
@mdubya66 I will include more test cases for this scenario. When does this need to be merged by?

**Comment by mdubya66** [comment]
Cutoff for 1.3.1 RC1 is end of today so we can spin the RC1 tomorrow morning

**Comment by jooskim** [comment]
@mdubya66 I will be able to close this PR after I am done writing test cases, but I already tested it manually and confirmed the bug was fixed. I'll update you on the progress.

**Comment by mdubya66** [comment]
I'm fine with a follow on PR with the tests as long as the manual tests passed.

**Comment by jooskim** [comment]
Added Protractor test cases and confirmed locally the tests pass.
```
  VCH Create Wizard with multiple DV Switches
    ✓ should redirect to login
    ✓ should login
    ✓ should navigate to vsphere home
    ✓ should navigate to vic plugin
    ✓ should navigate to summary tab
    ✓ should navigate to vch tab
    ✓ should open create vch wizard
    ✓ should input vch name
    ✓ should complete general step
    ✓ should select "Cluster" as compute resource
    ✓ should complete compute capacity step
[00:31:02] W/element - more than one element found for locator by.cssContainingText("select#image-store-selector option", "datastore1") - the first result will be used
    ✓ should select a datastore
    ✓ should complete storage capacity step
    ✓ should select a bridge network
[00:31:03] W/element - more than one element found for locator by.cssContainingText("select#public-network-selector option", "network") - the first result will be used
    ✓ should select a public network
    ✓ should navigate back to compute capacity step
    ✓ should select "10.162.46.79" as compute resource
    ✓ should select "net1" as bridge network
    ✓ should select "net2" as public network
    ✓ should complete networks step
    ✓ should complete security step
    ✓ should complete registry access step
    ✓ should enter ops user creds
    ✓ should complete ops user step
    ✓ should create a vch
.pagination-next not found
    ✓ should find the new vch in datagrid
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Power On virtual machine: virtual-container-host-449: 01/19/2018, 12:31:15 AM
Reconfigure virtual machine: virtual-container-host-449: 01/19/2018, 12:31:38 AM
    ✓ should verify the new vch has properly started
    ✓ should delete created vch
Delete resource pool: virtual-container-host-449: 01/19/2018, 12:31:52 AM
    ✓ should verify the created vch has been deleted

Executed 29 of 29 specs SUCCESS in 1 min 25 secs.
[00:31:54] I/launcher - 0 instance(s) of WebDriver still running
[00:31:54] I/launcher - chrome #01 passed
```

**Comment by cristianfalcone** [comment]
Network step hangs in our dev environment...

screen shot 2018-01-19 at 12 06 24
screen shot 2018-01-19 at 12 05 16
screen shot 2018-01-19 at 12 06 59
screen shot 2018-01-19 at 12 06 05

**Comment by jooskim** [comment]
@cristianfalcone It seems the H5 Client included in the SDK you are using is obsolete (6.5.0.5300) that the H5C API method to get DVS hosts information does not work as expected.

**Comment by cristianfalcone** [comment]
Thanks @jooskim! I updated my SDK and now it works.

**Comment by cristianfalcone** [comment]
LGTM

**Comment by stuclem** [comment]
@jooskim and @cristianfalcone I'm not sure what the actual issue is. Is it that if you go through the wizard to the networking page, configure bridge/public, then go back to a previous page and change some config,  when you return the networks page, the page doesn't load?

**Comment by stuclem** [comment]
Added as a resolved issue in the 1.3.1 RNs.

**Pull request merged**
