### PR TITLE
Fix always passing nightly tests on Jenkins

### LINKED ISSUE #17: UI integration test job on Jenkins should fail if any test case fails
I recently set up a job on our Jenkins server to run UI integration tests nightly. Since setting up the job, we had two runs each of which clearly had some failed cases. However, the failures were not properly accounted for, as the script ended with 0 return code. This behavior should be corrected.

### PR DESCRIPTION
**Pull request by jooskim**
Fixes #17

### CODE REVIEW

**Comment by mhagen-vmware** [comment]
```
anon@anon-Latitude-E7450:~$ pybot test.robot 
==============================================================================
Test                                                                          
==============================================================================
test                                                                  | FAIL |
AssertionError
------------------------------------------------------------------------------
test2                                                                 | PASS |
test
------------------------------------------------------------------------------
Test                                                                  | FAIL |
2 critical tests, 1 passed, 1 failed
2 tests total, 1 passed, 1 failed
==============================================================================
Output:  /home/anon/output.xml
Log:     /home/anon/log.html
Report:  /home/anon/report.html
anon@anon-Latitude-E7450:~$ echo $?
1
```

**Comment by jooskim** [comment]
@mhagen-vmware I know that, but the reason I explicitly put a keyword to make the `kickoff-tests.robot` script fail is that each run (either `Run Script Test With Config` or `Run Plugin Test With Config` keyword) does not fail.

**Comment by jooskim** [comment]
If you want the both keywords to fail thus letting the robot script report the failure state by itself, I could update the script, but why change when it's already working?

**Comment by mhagen-vmware** [comment]
no reason to change, just making sure you knew that robot handled the RC correctly by itself

**Comment by jooskim** [comment]
Cool, that's why I left the Jenkins job script unchanged with its last command being `robot`

**Pull request merged**
