### PR TITLE
Update Network step layout and fields

### LINKED ISSUE #70: Re-organize the networking tab
Public/Bridge/Management/Client networks and proxy settings are for the Endpoint VM (i.e., the VCH itself), but the Container Networks are for the Container VMs. However, the container network settings are placed between the other two, making it unclear which settings are used by each entity.

Additionally, things with the same label might not actually be the same; "Static" for a network on the VCH is for the (single) address to assign to the Endpoint VM, but "Static" for a Container Network is actually an IP _range_ that the VCH will assign to the Container VMs it creates.

Match the compute configuration, where there are sub-sections for container settings and endpoint settings.

### LINKED ISSUE #123: VCH UI doc link points to 1.1 docs
@cristianfalcone I just noticed that the link to **VIEW NETWORK REQUIREMENTS** points to the 1.1 docs:

11docs

Please can you update this to https://vmware.github.io/vic-product/assets/files/html/1.3/vic_vsphere_admin/vch_networking.html

Thanks!

### PR DESCRIPTION
**Pull request by cristianfalcone**
- Reorganize Network fields
 - Add firewall policy field to container networks

Fixes #70 
Fixes #123

### CODE REVIEW

**Comment by jak-atx** [comment]
@cristianfalcone please rebase your branch with master and make sure you are able to successfully run the integration tests against this update. 

cd h5c/vic/src/vic-webapp 
ng e2e

**Comment by cristianfalcone** [comment]
@jak-atx rebased with master and e2e tests passing.

**Comment by jak-atx** [comment]
@cristianfalcone It looks like the labels under 'Optional Container Networks' are misaligned. DNS, Label, Firewall policy labels should be left aligned. 

screen shot 2017-11-30 at 1 43 37 pm

**Comment by cristianfalcone** [comment]
screen shot 2017-11-30 at 17 03 14

**Pull request merged**
